### ISSUE TITLE
Rename feedstock?

### ISSUE THREAD

**Issue by jjhelmus** [conda-forge/python-decorator-feedstock#8]
Given that this package is named `decorator` would be make sense to change the repository name to `decorator-feedstock` rather than the current `python-decorator-feedstock`?

**Comment by ocefpaf** [comment]
The important thing was to rename the package, and we already [did that](https://github.com/conda-forge/python-decorator-feedstock/commit/d123a9ef68aeb791e345401d4a0e8c7dfa9f06d5). But I agree that it would be nice to rename the feedstock as well. Not sure if renaming will cause a mismatch with the `feedstocks` repo and how bad that would be...

**Comment by jjhelmus** [comment]
@ocefpaf I agree completely that renaming the packages was the more important change.  Renaming the feedstock would be nice but if it causes issued with other repositories then I don't think it it worth the effort.

**Comment by ocefpaf** [comment]
We can always delete and re-add. I'll investigate our options and come back with more info. (But if you find a package with a prefix that needs renaming let me know.)

**Comment by ocefpaf** [comment]
This feedstock will be removed and re-added with the `pathlib2` name once https://github.com/conda-forge/staged-recipes/pull/3554 is merged.

Ping @conda-forge/python-decorator

**Comment by ocefpaf** [comment]
Removing this feedstock now that https://github.com/conda-forge/staged-recipes/pull/3554 got merged.
